server {
    listen 80;
    listen [::]:80;
    server_name book.azoraengine.org;

    root /var/www/book.azoraengine.org/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
