import {
  ApplicationHost,
  Architecture,
  FirstApplication,
  Installation,
  Packages,
  Welcome,
} from './Foundations.jsx'
import {
  EcsOverview,
  EcsPatterns,
  EntitiesAndStorage,
  QueriesAndSystems,
  ResourcesEventsCommands,
  TimeAndScheduling,
} from './Ecs.jsx'
import {
  Audio,
  CamerasAndMath,
  Input,
  MeshesMaterialsQueues,
  RenderingOverview,
  ShadersAndBackends,
  TwoDimensionalRendering,
} from './Rendering.jsx'

export const sections = [
  {
    id: 'welcome',
    number: '1',
    title: 'Welcome',
    depth: 0,
    keywords: 'introduction engine Azora application game framework',
    component: Welcome,
  },
  {
    id: 'architecture',
    number: '1.1',
    title: 'Architecture',
    depth: 1,
    keywords: 'world storage schedule app engine signal frame pipeline',
    component: Architecture,
  },
  {
    id: 'installation',
    number: '1.2',
    title: 'Installation & Projects',
    depth: 1,
    keywords: 'install package azpm manifest project template build',
    component: Installation,
  },
  {
    id: 'first-application',
    number: '1.3',
    title: 'Your First Application',
    depth: 1,
    keywords: 'window frame loop present shutdown lifecycle',
    component: FirstApplication,
  },
  {
    id: 'engine-host',
    number: '1.4',
    title: 'The Engine Host',
    depth: 1,
    keywords: 'host game system scheduled system run',
    component: ApplicationHost,
  },
  {
    id: 'packages-imports',
    number: '1.5',
    title: 'Packages & Imports',
    depth: 1,
    keywords: 'packages imports dependencies facade focused modules',
    component: Packages,
  },
  {
    id: 'ecs',
    number: '2',
    title: 'Entity Component System',
    depth: 0,
    keywords: 'ecs entity component system resource data oriented',
    component: EcsOverview,
  },
  {
    id: 'entities-storage',
    number: '2.1',
    title: 'Entities, Components & Storage',
    depth: 1,
    keywords: 'entity generation storage component spawn despawn hierarchy',
    component: EntitiesAndStorage,
  },
  {
    id: 'queries-systems',
    number: '2.2',
    title: 'Queries & Systems',
    depth: 1,
    keywords: 'query system access scheduler parallel change tracking',
    component: QueriesAndSystems,
  },
  {
    id: 'resources-events-commands',
    number: '2.3',
    title: 'Resources, Events & Commands',
    depth: 1,
    keywords: 'resource event queue command buffer deferred mutation',
    component: ResourcesEventsCommands,
  },
  {
    id: 'time-scheduling',
    number: '2.4',
    title: 'Time, Phases & Fixed Updates',
    depth: 1,
    keywords: 'time phase schedule fixed update timestep deterministic',
    component: TimeAndScheduling,
  },
  {
    id: 'ecs-patterns',
    number: '2.5',
    title: 'ECS Design Patterns',
    depth: 1,
    keywords: 'ecs design state transition component event system pattern',
    component: EcsPatterns,
  },
  {
    id: 'rendering',
    number: '3',
    title: 'Rendering',
    depth: 0,
    keywords: 'render gpu metal webgl mesh camera',
    component: RenderingOverview,
  },
  {
    id: 'meshes-materials-queues',
    number: '3.1',
    title: 'Meshes, Materials & Queues',
    depth: 1,
    keywords: 'mesh material render queue cube cylinder grid',
    component: MeshesMaterialsQueues,
  },
  {
    id: 'cameras-transforms-math',
    number: '3.2',
    title: 'Cameras, Transforms & Math',
    depth: 1,
    keywords: 'camera transform vector matrix projection movement',
    component: CamerasAndMath,
  },
  {
    id: 'rendering-2d',
    number: '3.3',
    title: '2D, Textures & Sprites',
    depth: 1,
    keywords: '2d texture sprite atlas ui region',
    component: TwoDimensionalRendering,
  },
  {
    id: 'shaders-backends',
    number: '3.4',
    title: 'Shaders & Render Backends',
    depth: 1,
    keywords: 'shader metal vulkan webgl wasm backend',
    component: ShadersAndBackends,
  },
  {
    id: 'input',
    number: '3.5',
    title: 'Input',
    depth: 1,
    keywords: 'input keyboard mouse pointer touch gamepad controller',
    component: Input,
  },
  {
    id: 'audio',
    number: '3.6',
    title: 'Audio',
    depth: 1,
    keywords: 'audio sound music volume playback resource',
    component: Audio,
  },
]
